p = migraphx.program()
m = p.get_main_module()
p_x88 = m.add_parameter("x88", migraphx.shape(type="float_type", lens=[$m$, $k1$]))
x_1 = m.add_literal(migraphx.generate_argument(migraphx.shape(type="float_type", lens=[$n1k2$, $n2$]), 0))
x_2 = m.add_literal(migraphx.generate_argument(migraphx.shape(type="float_type", lens=[$k1$, $n1k2$]), 4))
x_3 = m.add_literal(migraphx.generate_argument(migraphx.shape(type="float_type", lens=[$m$, $n1k2$]), 5))
x_4 = m.add_instruction(migraphx.op("dot"), [p_x88, x_2]) # migraphx.shape(type="float_type", lens=[$m$, $n1k2$])
x_5 = m.add_instruction(migraphx.op("mul"), [x_3, x_4]) # migraphx.shape(type="float_type", lens=[$m$, $n1k2$])
m.add_instruction(migraphx.op("dot"), [x_5, x_1]) # migraphx.shape(type="float_type", lens=[$m$, $n2$])
